application: fluid-honor-669
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: .*
  script: myproject.wsgi.application

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

libraries:
- name: django
  version: 1.5

